# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a8025a9a2b11798f347b855049f9eed3aefb7314c0b1c08aa6c28ea24de4984dc10dbf3a20b4d1d805bfbb067efbad237aafebf657aca9f55e5a6816f967174

test:
  secret_key_base: 22c927db2fb1291f481dd6b7aa0a44e28a788caf6c61730914afba3c16814854ec4c41f58e09a3dd3500d1258f2d5df1ae22cb09e43849d5f84ad1afa6b41a74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
